"""Pydantic models for AI structured output."""

from pydantic import BaseModel, Field
from typing import List, Optional


class InfobitDefinition(BaseModel):
    """Single infobit field definition generated by AI."""

    field_name: str = Field(description="Machine-readable identifier, e.g. 'company_name'")
    field_label: str = Field(description="Human-readable label in Estonian")
    field_label_en: str = Field(description="Human-readable label in English")
    field_description: str = Field(description="Help text explaining what information is needed")
    category: str = Field(description="Category: general, company, project, budget, team, timeline, outcomes")
    is_required: bool = Field(description="Whether this field is mandatory")
    sort_order: int = Field(description="Display order within category")


class GeneratedInfobits(BaseModel):
    """Complete set of infobits generated for a project."""

    infobits: List[InfobitDefinition]
    reasoning: str = Field(description="Brief explanation of why these fields were identified")


class ExtractedInfobitValue(BaseModel):
    """Single extracted value from document."""

    field_name: str = Field(description="Target infobit field_name")
    extracted_value: str = Field(description="The extracted text value")
    confidence: float = Field(description="Confidence score 0.0-1.0")
    source_text: str = Field(description="Original text snippet from document")


class DocumentExtraction(BaseModel):
    """AI extraction results from uploaded document."""

    extractions: List[ExtractedInfobitValue]
    unmatched_info: List[str] = Field(
        default_factory=list,
        description="Useful info found but no matching field"
    )


class RequirementItem(BaseModel):
    """Single requirement item extracted from grant documentation."""

    name: str = Field(description="Requirement name/title")
    description: str = Field(description="Detailed description of what is required")
    is_mandatory: bool = Field(description="Whether this requirement is mandatory")
    category: str = Field(description="Category: document, eligibility, budget, timeline, technical")


class ExtractedRequirements(BaseModel):
    """Requirements extracted from grant documentation."""

    requirements: List[RequirementItem]
    summary: str = Field(description="Brief summary of the grant requirements")


class DocumentEvaluation(BaseModel):
    """AI evaluation of a user document against requirements."""

    score: float = Field(description="Overall score 1-10")
    summary: str = Field(description="Brief summary of the document")
    strengths: List[str] = Field(description="List of strengths")
    weaknesses: List[str] = Field(description="List of areas needing improvement")
    recommendations: List[str] = Field(description="Specific recommendations for improvement")
    requirement_coverage: List[str] = Field(
        default_factory=list,
        description="List of requirements this document addresses"
    )
